# Generated by Django 5.1.6 on 2025-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.IntegerField()),
                ('is_my_field', models.BooleanField()),
                ('name_field', models.CharField(max_length=50)),
                ('date_field', models.DateField()),
            ],
            options={
                'verbose_name': 'MyModel',
                'verbose_name_plural': 'MyModels',
            },
        ),
    ]
